
[terminal.shell]

program = "/bin/zsh"
args = ["-l", "-c", "tmux a -t 0 || tmux"]

[window]

padding = { x = 5, y = 5 }

[font]

normal = { family = "hackgen", style = "Regular" }
size = 13
offset = { x = 1, y = 2 }
glyph_offset = { y = 1 }

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/themes/themes/nightfox.toml"
]

[terminal]
